-- Avcı Commerce ortak kataloğundaki, BasBitir pilotunda doğrulanan yeniden kullanılabilir modüller.
-- INSERT OR IGNORE yönetici tarafından daha önce düzenlenmiş katalog kayıtlarını korur.
INSERT OR IGNORE INTO `modules` (`name`, `slug`, `category`, `summary`, `features`, `price_note`, `sort_order`, `status`) VALUES
  ('PrintCommerce', 'print-commerce', 'ozel', 'Matbaa ürünleri, baskı seçenekleri ve üretim dosyaları için sektörel Commerce modülü.', 'Dinamik baskı seçenekleri\nCanlı fiyat ve üretim bilgileri\nDosya gereksinimleri\nTenant bazlı matbaa presetleri', 'Lisans ve kurulum kapsamına göre', 400, 'live'),
  ('Avcı Tasarım Stüdyosu', 'design-studio', 'ozel', 'Şablon, metin, görsel, arka plan ve marka kitiyle ürün tasarlama akışı.', 'Kendin Tasarla\nŞablon ve arka plan kütüphanesi\nMarka kiti\nBaskıya hazır dosya akışı', 'Pro modül · lisansla etkinleşir', 410, 'live'),
  ('3D Ürün ve Mockup Sunumu', 'print-preview-3d', 'ozel', 'Tasarımı kartvizit, bardak, kutu ve benzeri ürün yüzeylerinde önizler.', 'Mağaza tarafından yüklenen mockup\nPNG baskı yüzeyi\nCanlı 3D önizleme\nÜrün bazlı açma/kapatma', 'Pro modül · lisansla etkinleşir', 420, 'live'),
  ('Şeffaf Üretim ve Baskı Onayı', 'print-approval', 'ozel', 'Dosya kontrolü, müşteri onayı, revizyon ve üretim aşamalarını görünür kılar.', 'Dosya ön kontrolü\nMüşteri onay bağlantısı\nRevizyon akışı\nCanlı üretim aşamaları', 'PrintCommerce eklentisi', 430, 'live'),
  ('Büyüme ve Akıllı Vitrin', 'growth-commerce', 'ozel', 'Akıllı öneri, numune ürünü, sektör paketi ve teklif akışlarını yönetir.', 'Akıllı ürün önerileri\nNumune ürünleri\nSektör paketleri\nTekliften sepete geçiş', 'Lisans ve kullanım kapsamına göre', 440, 'live'),
  ('Müşteri Çalışma Alanı', 'customer-workspace', 'ozel', 'Sipariş, tasarım, marka kiti, onay, adres ve bildirimleri tek hesapta toplar.', 'Canlı sipariş takibi\nTasarımlarım\nMarka kitim\nOnay talepleri ve tercihler', 'Mağaza paketine eklenir', 450, 'live'),
  ('Avcı Topluluk', 'community', 'ozel', 'Doğrulanmış sipariş rozetleri, rütbeler, paylaşımlar ve moderasyon sunar.', 'Sipariş doğrulamalı rozetler\nRütbe ve avantajlar\nTasarımcı katkıları\nİçerik moderasyonu', 'Topluluk modülü · lisansla etkinleşir', 460, 'live'),
  ('Avcı Pro Sayfa Tasarımcısı', 'pro-page-builder', 'ozel', 'Vitrin ve izin verilen yönetim ekranlarını görsel bileşenlerle düzenler.', 'Sürükle bırak sayfa düzenleme\nTenant sayfa sürümleri\nÖnizleme ve yayınlama\nYetki ve lisans kontrolü', 'Avcı Commerce Pro modülü', 470, 'live'),
  ('WhatsApp Satış ve Destek', 'whatsapp-support', 'ozel', 'Mağaza bazlı destek bileşeni, teklif bağlantısı ve hazır mesaj akışları sağlar.', 'Sabit destek bileşeni\nÇalışma saatleri\nÜrün ve teklif bağlantıları\nHazır mesaj şablonları', 'Lisansla açılır ve mağaza bazında ayarlanır', 480, 'live');
