import { packageEntitlements } from "./checkout-entitlements.mjs";
export const escapeHtml = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const isTestView = env => ["development","test"].includes(env.NODE_ENV);
export function checkoutShell(title, content, env, step=1) {
  const test = isTestView(env);
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="robots" content="noindex,nofollow"><title>${escapeHtml(title)} | Avcı E-Ticaret</title><link rel="stylesheet" href="/checkout-assets/style.css"><script src="/checkout-assets/ui.js" defer></script></head><body><a class="skip" href="#main">İçeriğe geç</a><header class="site-top"><a href="/checkout" aria-label="Avcı E-Ticaret"><img src="/checkout-assets/logo.png" alt="Avcı E-Ticaret" width="220" height="60"></a><span class="header-note">MÜŞTERİ MERKEZİ <span aria-hidden="true">↗</span></span></header>${test?'<div class="test-notice">Geliştirme önizlemesi <span>Gerçek tahsilat yapılmaz.</span></div>':''}<main id="main"><ol class="steps" aria-label="Satın alma adımları">${["Paket & bilgiler","Ödeme onayı","Hesabın hazır"].map((label,i)=>`<li ${i+1===step?'aria-current="step"':''} class="${i+1<=step?'active':''}"><span>${i+1<step?'✓':i+1}</span>${label}</li>`).join('')}</ol>${content}</main><footer><strong>Avcı E-Ticaret</strong><span>İşiniz büyürken, altyapınız yanınızda.</span><span>Hesap & lisans merkezi</span></footer></body></html>`;
}
const alertBox = '<div id="result" class="notice" role="status" aria-live="polite" tabindex="-1" hidden><strong id="result-title"></strong><p id="result-copy"></p></div>';
export function checkoutView(options,env) {
  const panels=options.map((x,i)=>`<section class="plan-summary" data-plan="${escapeHtml(x.slug)}" ${i?'hidden':''}><div class="summary-top"><span class="eyebrow">SEÇTİĞİNİZ PAKET</span><span class="plan-tag">${escapeHtml(x.name)}</span></div><h2>İşinize uygun.<br>Size ait bir alan.</h2><div class="price">${(x.price_amount_kurus/100).toLocaleString('tr-TR')} <span>TL</span></div><p class="price-note">KDV dahil · ${x.license_duration_days} gün lisans</p><hr><h3>Paketinize dahil</h3><ul class="rights">${packageEntitlements(x.slug).groups.map(g=>`<li><span aria-hidden="true">✓</span>${escapeHtml(g.label)}</li>`).join('')}</ul><div class="summary-foot">Domaininize bağlı lisans<br><span>Ödeme onayıyla hesabınıza tanımlanır.</span></div></section>`).join('');
  return checkoutShell("Paketini domainine bağla",`<div class="flow-grid"><section class="form-card"><span class="eyebrow">YENİ BAŞLANGICINIZ</span><h1>Paketini domainine bağla<span class="red">.</span></h1><p class="intro">İşletmenizin bilgilerini tamamlayın. Ödeme onayından sonra lisansınız seçtiğiniz domaine bağlansın.</p><form id="checkout-form" novalidate><label for="packageSlug">Paketiniz</label><select id="packageSlug" name="packageSlug">${options.map(x=>`<option value="${escapeHtml(x.slug)}">${escapeHtml(x.name)}</option>`).join('')}</select><div class="field-grid"><div><label for="name">Ad soyad</label><input id="name" name="name" required minlength="2" maxlength="60" autocomplete="name" placeholder="Adınız ve soyadınız"></div><div><label for="email">E-posta adresi</label><input id="email" name="email" type="email" required autocomplete="email" placeholder="siz@isletmeniz.com"></div></div><label for="domain">Mağazanızın domaini</label><input id="domain" name="domain" required placeholder="magazam.com" autocapitalize="none" spellcheck="false" aria-describedby="domain-help"><p id="domain-help" class="help">https:// veya sayfa adresi eklemeyin. Lisansınız bu domaine tanımlanır.</p>${alertBox}<button class="primary" type="submit">Bilgileri onayla ve devam et <span aria-hidden="true">→</span></button><p class="form-foot">Parolanızı, e-postanıza gönderilen tek kullanımlık bağlantıyla belirleyeceksiniz.</p></form></section><aside>${panels}</aside></div>`,env);
}
export function passwordView(env) {
  return checkoutShell("Parolanı belirle",`<div class="flow-grid password-grid"><section class="form-card"><span class="eyebrow">SON BİR ADIM</span><h1>Parolanı belirle<span class="red">.</span></h1><p class="intro">Hesabınıza yalnız sizin erişebilmeniz için güçlü bir parola seçin.</p><form id="password-form" novalidate><label for="password">Yeni parola</label><div class="password-wrap"><input id="password" name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password" aria-describedby="password-rules"><button id="show-password" type="button" aria-label="Parolayı göster" aria-pressed="false">Göster</button></div><ul id="password-rules" class="password-rules"><li data-rule="length">En az 12 karakter</li><li data-rule="case">Büyük ve küçük harf</li><li data-rule="number">En az bir rakam</li></ul><label for="confirm">Parolanızı tekrar yazın</label><input id="confirm" name="confirm" type="password" required autocomplete="new-password">${alertBox}<button class="primary" type="submit">Parolamı kaydet <span aria-hidden="true">→</span></button><p class="form-foot">Bağlantınız tek kullanımlıktır ve 30 dakika geçerlidir.</p></form><div id="password-done" hidden class="success-copy"><span class="state-icon success">✓</span><h2>Hesabınız hazır.</h2><p>Parolanız kaydedildi. Artık hesabınıza belirlediğiniz parolayla giriş yapabilirsiniz.</p></div></section><aside class="account-note"><span class="eyebrow">AVCI MÜŞTERİ MERKEZİ</span><h2>Her şey,<br>tek hesabınızda.</h2><p>Lisansınız, paket kapsamınız ve hizmetleriniz için size ait bir merkez.</p><ol><li><b>01</b><span>Domaininize bağlı lisans</span></li><li><b>02</b><span>Paketinize özel modüller</span></li><li><b>03</b><span>Hesap ve destek yönetimi</span></li></ol></aside></div>`,env,3);
}
export function resultView(status,env,preview=false) {
  const states={paid:["✓","Ödemeniz onaylandı.","Lisansınız domaininize bağlandı. Hesabınızı tamamlamak için e-postanıza gönderilen parola belirleme bağlantısını kullanın.","success",3],failed:["!","Ödeme tamamlanamadı.","Bu ödeme için lisans veya yeni hesap oluşturulmadı. Bilgilerinizi kontrol ederek yeniden deneyebilirsiniz.","error",2],pending:["…","Ödeme onayı bekleniyor.","Siparişiniz hazır. Ödeme sağlayıcısının onayı henüz ulaşmadı. Onay gelmeden hesabınız veya lisansınız oluşturulmaz.","pending",2],missing:["?","Sipariş bulunamadı.","Bağlantı eksik veya geçersiz olabilir. Paket seçimine dönerek tekrar başlayabilirsiniz.","error",1]};
  const [icon,title,copy,tone,step]=Object.hasOwn(states,status)?states[status]:states.missing;
  preview = preview && isTestView(env);
  return checkoutShell(title,`<section class="result-card"><span class="state-icon ${tone}" aria-hidden="true">${icon}</span><span class="eyebrow">${preview?'TASARIM ÖNİZLEMESİ':'SİPARİŞ DURUMU'}</span><h1>${title}</h1><p class="intro">${copy}</p>${status==='paid'?'<div class="next-step"><strong>Sıradaki adım: e-postanızı kontrol edin</strong><p>Gelen kutunuzda göremiyorsanız spam klasörüne de bakın. Mevcut hesabınız varsa parolanız değişmez.</p></div>':''}<a class="primary" href="/checkout">${status==='failed'?'Yeniden dene':'Paketlere dön'} <span aria-hidden="true">→</span></a>${status==='pending'?'<button class="secondary" id="refresh-status">Durumu yenile</button>':''}</section>`,env,step);
}
