import { asc, desc, eq } from "drizzle-orm";
import { avciMobileApps, commerceLicenseInstallations, customerMobileAppAssignments, customers } from "../../../../../db/schema";
import { logAdminAction } from "../../../../audit-log.mjs";
import { authorizeControlDesk, controlDeskJson, hasControlDeskRole } from "../../../../control-desk-auth.mjs";
import { ensureCommerceLicenseTables } from "../../../../local-d1-schema.mjs";
const clean=(value:unknown,max=300)=>String(value??"").trim().slice(0,max);const keyOf=(value:unknown)=>clean(value,72).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"");
export async function GET(request:Request){const auth=await authorizeControlDesk(request);if(!auth.ok)return controlDeskJson({ok:false,error:auth.error},auth.status,request);await ensureCommerceLicenseTables(auth.env);const {getDb}=await import("../../../../../db");const db=getDb();const apps=await db.select().from(avciMobileApps).orderBy(asc(avciMobileApps.name),asc(avciMobileApps.platform));const assignments=auth.customerId?await db.select().from(customerMobileAppAssignments).where(eq(customerMobileAppAssignments.customerId,auth.customerId)).orderBy(desc(customerMobileAppAssignments.updatedAt)):await db.select().from(customerMobileAppAssignments).orderBy(desc(customerMobileAppAssignments.updatedAt)).limit(1000);return controlDeskJson({ok:true,format:"avci-control-desk.mobile-apps.v1",apps:apps.filter((item)=>!auth.customerId||assignments.some((a)=>a.mobileAppId===item.id)),assignments,capabilities:{write:hasControlDeskRole(auth,["platform_owner"]),assign:hasControlDeskRole(auth,["platform_owner","installer"])}},200,request);}
export async function POST(request:Request){const auth=await authorizeControlDesk(request);if(!auth.ok)return controlDeskJson({ok:false,error:auth.error},auth.status,request);const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return controlDeskJson({ok:false,error:"Geçersiz istek."},400,request);const action=clean(body.action,20);if(!hasControlDeskRole(auth,action==="assign"?["platform_owner","installer"]:["platform_owner"]))return controlDeskJson({ok:false,error:"Mobil uygulama işlem yetkiniz yok."},403,request);await ensureCommerceLicenseTables(auth.env);const {getDb}=await import("../../../../../db");const db=getDb(),now=new Date().toISOString();
if(action==="create"){const appKey=keyOf(body.appKey||body.name),name=clean(body.name,120),platform=clean(body.platform,12),bundleId=clean(body.bundleId,180);if(!appKey||!name||!["ios","android"].includes(platform)||!bundleId)return controlDeskJson({ok:false,error:"Ad, platform ve paket kimliği gereklidir."},400,request);const inserted=await db.insert(avciMobileApps).values({appKey,name,platform,bundleId,currentVersion:clean(body.currentVersion,30)||"1.0.0",buildNumber:clean(body.buildNumber,30)||"1",releaseChannel:clean(body.releaseChannel,30)||"production",storeStatus:clean(body.storeStatus,20)||"draft",storeUrl:/^https:\/\//i.test(clean(body.storeUrl,500))?clean(body.storeUrl,500):"",healthStatus:"unknown",minimumOsVersion:clean(body.minimumOsVersion,30),notes:clean(body.notes,1000),createdAt:now,updatedAt:now}).returning({id:avciMobileApps.id});await logAdminAction(db,{userEmail:auth.email,action:"mobile_app_created",entity:"avci_mobile_app",entityId:String(inserted[0]?.id||""),details:JSON.stringify({appKey,platform})});return controlDeskJson({ok:true,id:inserted[0]?.id},201,request);}
if(action==="assign"){const customerId=Number(body.customerId),mobileAppId=Number(body.mobileAppId),licenseId=Number(body.licenseId)||0;if(!Number.isSafeInteger(customerId)||!Number.isSafeInteger(mobileAppId))return controlDeskJson({ok:false,error:"Müşteri ve uygulama seçimi gerekli."},400,request);const [[customer],[mobileApp],licenses]=await Promise.all([db.select({id:customers.id}).from(customers).where(eq(customers.id,customerId)).limit(1),db.select({id:avciMobileApps.id,status:avciMobileApps.status}).from(avciMobileApps).where(eq(avciMobileApps.id,mobileAppId)).limit(1),licenseId?db.select({id:commerceLicenseInstallations.id,customerId:commerceLicenseInstallations.customerId,status:commerceLicenseInstallations.status}).from(commerceLicenseInstallations).where(eq(commerceLicenseInstallations.id,licenseId)).limit(1):Promise.resolve([])]);if(!customer||!mobileApp||mobileApp.status!=="active")return controlDeskJson({ok:false,error:"Aktif müşteri veya mobil uygulama bulunamadı."},404,request);if(licenseId&&(!licenses[0]||licenses[0].customerId!==customerId||!["active","trial"].includes(licenses[0].status)))return controlDeskJson({ok:false,error:"Seçilen lisans bu müşteriye ait ve aktif olmalıdır."},409,request);try{const inserted=await db.insert(customerMobileAppAssignments).values({customerId,mobileAppId,licenseId,brandedName:clean(body.brandedName,120),assignedAt:now,updatedAt:now}).returning({id:customerMobileAppAssignments.id});await logAdminAction(db,{userEmail:auth.email,action:"mobile_app_assigned",entity:"customer_mobile_app_assignment",entityId:String(inserted[0]?.id||""),details:JSON.stringify({customerId,mobileAppId,licenseId})});return controlDeskJson({ok:true,id:inserted[0]?.id},201,request);}catch{return controlDeskJson({ok:false,error:"Bu mobil uygulama müşteriye zaten atanmış."},409,request);}}
return controlDeskJson({ok:false,error:"Desteklenmeyen işlem."},400,request);}
